# This file is machine-generated - editing it directly is not advised

[[CEnum]]
git-tree-sha1 = "215a9aa4a1f23fbd05b92769fdd62559488d70e9"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.1"

[[LibOnnxRuntime]]
deps = ["CEnum"]
git-tree-sha1 = "825ca5b81675679ae19f702f5ba893f81cc45f99"
repo-rev = "main"
repo-url = "https://github.com/IanET/LibOnnxRuntime.git"
uuid = "edd8e961-822f-4801-b21c-cac5f01a00fa"
version = "0.1.0"
